### ISSUE TITLE
Question for understanding, before install

### ISSUE THREAD

**Issue by DarkSir23** [Mydayyy/Valheim-ServerSideMap#16]
One of my players asks:

what happens to people's existing maps and points of interest? do I lose everything? do everyone's existing POIs upload and stack on the server map?

It's really this last part that I'm wondering about.  If we install it after several people have been playing, how does that work?

**Comment by Mydayyy** [comment]
Greetings,

it will behave as follows:

Map:
- All connecting clients will upload their current exploration progress to the server. The server merges it into his map. Once explored, an area is never set to unexplored again. E.g if client1 has the entire left side explored and client2 has the entire right side explored, the server would hold  a fully explored map.
- All connecting clients will download the explored map when connecting and apply it to their local map. Again, in a non destructive manner meaning areas are never set to unexplored
- As usual, while playing all clients will receive live updates from other players who are out exploring

Pins:
- Already existing pins of the client are not touched, the share only applies to newly created pins on this server.
- When connecting, the server sends all current existing pins to the client and the client shows them on the map.
- Every newly created pin only exists on the server, the client receives them when connecting
- Everyone can delete/check/uncheck a pin (that was created after installing the mod) and it is synchronized in realtime. Meaning when you look at your map and someone checks a pin, you'll immediately see it too.


This also means the following:
- If you disable the mod, you wont see all pins you created while you had this mod - since they are existing on the server now and are saved along with the map 

Please note that the server definitely needs the mod too, since he is the main authority.

**Comment by DarkSir23** [comment]
Perfect, thanks.  And I believe I read that you could share maps without sharing pins, is that correct?

**Comment by Mydayyy** [comment]
Yes it is.

After your first start with the plugin enabled, a config file will be created, you can adjust map share and pin share separately there.

Map share defaults to true 
Pin share defaults to false

**Comment by JTF195** [comment]
Is there any way to manually "upload" pins to the server side pins?

**Comment by Mydayyy** [comment]
By that you mean to convert existing local pins to serverside pins?

**Comment by JTF195** [comment]
Yes

**Comment by Mydayyy** [comment]
That's certainly possible, I created an issue for it: #17
