### ISSUE TITLE
Introduce hotkey for sharing pins?

### ISSUE THREAD

**Issue by Amar1729** [Mydayyy/Valheim-ServerSideMap#39]
Is it possible this mod could introduce a hotkey for sharing pins (with/without dupes)?

I looked into a similar mod, Explore Together, that has [hotkeys for sharing map or pin progress](https://github.com/rolopogo/ValheimMods/blob/8cfc1a5d04757555dc668d4fa49f20946dcdf54a/ExploreTogether/ExploreTogether/Patches/Player.cs#L60-L67) but I'm not sure of all the code necessary to implement it in this mod.

**Comment by Mydayyy** [comment]
Greetings,

yes in theory this would be possible, I do have trouble seeing the use case for this currently. The goal is to sync the pins basically on creation to the server, so they only exist on the server instead of the client.

The only need to sync local pins to the server arises from mod-created pins (e.g locator, ...). This is currently possible via a chat command. Do you find yourself running this chat command often and are looking for a hotkey solution?

Best Regards
Mydayyy

**Comment by Amar1729** [comment]
Yup, a few friends and I are using Locator alongside this mod actually. We try to sync pins before we log out, but we're finding that ideally they would just be synced quietly/via hotkey while exploring.

Another problem that arises with the use of Locator specifically is that we end up having quite a few duplicate pins, and so some of us have been wanting a hotkey or config option for `/convertpins ignorelocaldupes` as well (although I get it if you feel its outside the scope of the mod).

**Comment by Mydayyy** [comment]
Sorry for the late reply, the weekend basically blew past me <.<

I'd love to implement this. From what I gather, another idea would be the ability to toggle a flag via the config, to automatically sync pins when logging out instead of a hotkey. What of those two do you think makes the most sense?

Best Regards
Mydayyy

**Comment by Mydayyy** [comment]
Hello,

I released a new RC here: [https://github.com/Mydayyy/Valheim-ServerSideMap/releases/tag/rc-1.3.3](https://github.com/Mydayyy/Valheim-ServerSideMap/releases/tag/rc-1.3.3)

To test the hotkey functionality, it is enough to only update the client. It is fully backwards compatible and you don't necessarily need to update the server right away. I will implement the auto-sync on logout functionality on the weekend.

Best Regards
Mydayyy

**Comment by Mydayyy** [comment]
Went live in 1.3.5

**Comment by Amar1729** [comment]
Thanks very much for your work on this! Forgot to update this issue after trying it out.
