### ISSUE TITLE
FPS and/or network lag while browsing the map zoomed out

### ISSUE THREAD

**Issue by roxorplox** [Mydayyy/Valheim-ServerSideMap#52]
I've noticed that while browsing the map when zoomed out even just a bit, there is significant FPS (and possibly some network) latency. Is this normal for this mod? Anything that can be done to fix this? Thanks for your support!

**Comment by Mydayyy** [comment]
Greetings,

Thats a bit puzzling for me since I would not know why this occurs. I will test this on the weekend and report back here.

Best Regards
Mydayyy

**Comment by roxorplox** [comment]
Hey! Thanks for testing this. Just for the record both the dedicated server
and myself are on 1Gb Fiber network connections. Server is very robust with
components. My PC is also very robust using a 3080Ti.

Try zooming out far, doesn't have to be all the way, make sure there are
plenty of pins on the map, and try pulling the map around quickly.

You can also see the fps lag while opening the map if it's zoomed out
already.

**Comment by Mydayyy** [comment]
Greetings,


unfortunately I failed to reproduce it. For me the map is working fine.

A few thoughts:
- The mod does not have any functionality which runs when the map is dragged. All it does is creating pins via the functions valheim uses itself too.
- How many pins are we talking about? And are there maybe a lot of duplicate pins in the same location which might cause strain?
- This should happen without the mod installed too, although if it is caused by the amount of pins the issue might go away once you uninstall it since the pins are not loaded from the server anymore. But if you are able to test it with the same amount of pins and without the mod I'd be interested in the result

Best Regards
Mydayyy

**Comment by roxorplox** [comment]
I think this has actually improved after restarting the server once, after
this mod was installed.
