### ISSUE TITLE
Not syncing to players

### ISSUE THREAD

**Issue by mLgz0rn** [Mydayyy/Valheim-ServerSideMap#54]
I can not seem to get this to work, the server does seem to sync.
But player maps does not update at all.

**Comment by Mydayyy** [comment]
Greetings,

do all players have the mod installed and can confirm that it is loaded correctly via logs?

Best Regards
Mydayyy

**Comment by mLgz0rn** [comment]
From my log:
```
[Info   :   BepInEx] Loading [ServerSideMap 1.3.8.0]
[Info   :ServerSideMap] Store1: False
[Info   :ServerSideMap] Store2: False
[Info   :ServerSideMap] ZNet awake
[Info   :ServerSideMap] Minimap awake
[Info   :ServerSideMap] Registered Client Events
[Info   :ServerSideMap] Client received initial pin data by server. Pins: 7
[Info   :ServerSideMap] ClientAppendPins 7
```

One my friends logs show the same

**Comment by mLgz0rn** [comment]
So I seem to have narrowed down what the issue is.

It seems to not be compatible with Webmap, that or removing crossplay hence using steamworks instead of playfab did it (got no idea about this one).

**Comment by Mydayyy** [comment]
Greetings,

I apologize for the late response; I fell asleep yesterday.

Yes, you are in fact right that crossplay introduces an incompatibility rendering my mod useless. It was actually discovered in the past by vp-en here: https://github.com/Mydayyy/Valheim-ServerSideMap/issues/47#issuecomment-1426843264

Unfortunately due to time constraints I did not yet investigate and fix this issue; the mod, since it got written before crossplay was not created with that option in mind.

I would welcome a PR on this topic so, if anyone finds himself willing to investigate this.

**Comment by Mydayyy** [comment]
Greetings,

I once again apologize for the late response here.

But you're absolutely right. I will add this to the README next weekend and keep this issue open until then.

Best Regards
Mydayyy

**Comment by Mydayyy** [comment]
Added to description in v1.3.9
