### ISSUE TITLE
[Warning: BepInEx] Skipping [ServerSideMap 1.3.9.0] because a newer version exists (ServerSideMap 1.3.9.0)

### ISSUE THREAD

**Issue by Benreuveni** [Mydayyy/Valheim-ServerSideMap#58]
I'm getting the following error" [Warning:   BepInEx] Skipping [ServerSideMap 1.3.9.0] because a newer version exists (ServerSideMap 1.3.9.0) [error_log.txt](https://github.com/Mydayyy/Valheim-ServerSideMap/files/12516093/error_log.txt)

I'm using r2modman with a profile that's shared between a dedicated server I'm hosting, and my own client. All other mods work as expected.

A few other questions:
- I've not been able to find the .explored file anywhere. I'm using
- Should the ServerSideMap.dll be placed in the BepInEx>Plugins folder, or in the BepInEx>Plugins>Mydayyy-ServerSideMap folder?
- Since I use r2modman I only have 1 single BepInEx folder. Does this interfere with this mod?

Thanks!

**Comment by Mydayyy** [comment]
Greetings,

thank you for your report. I'll be prefacing this by saying that I never used r2modman.

Let me answer the questions first:

> I've not been able to find the .explored file anywhere. I'm using
It should exist as a sibling to your world save file and be named as `WORLDNAME.mod.serversidemap.explored`. If the mod does not get loaded due to the above error the file would not exist

> Should the ServerSideMap.dll be placed in the BepInEx>Plugins folder, or in the BepInEx>Plugins>Mydayyy-ServerSideMap folder?
This should, to my knowledge, not make a difference. As far as I know the entire manual management is abstracted away from the user by r2modman. So putting it in a subfolder should be good as well

> Since I use r2modman I only have 1 single BepInEx folder. Does this interfere with this mod?
Isn't this the norm? I too only have one BepInEx folder.



To circle back to the main question:

I have never seen this error, upon googling it I found some answers relating to a double installation. Can you doublecheck that the mod is not installed twice?
